site_name: GenomicFlow API
site_description: Documentation for managing the Genomic Flow Application system.
repo_url: https://github.com/sansterbioanalytics/FlowAPI
theme:
  name: 'material'

markdown_extensions:
- fenced_code:
    syntax_highlight: true